#' Summarize the bootstrap results.
#' 
#' @param data The data frame containing the binary nodes and the individual characteristics
#'   for network construction. 
#' @param IsingBootResult The object generated by the IndivBootnet function.
#' @param IsingResult The fitted IndivIsing object.
#' @param nCores Number of cores to use in computing results. Set to 1 to not use parallel computing.
#'   Defaults to 1.
#' @param library Library location to be used in parallel computing. Default to .libPaths().
#' @param verbose Logical. Should progress of the function be printed to the console?
#'   Defaults to TRUE.
#' @param sample_covar_mat The matrix of covariate information for representative subjects toperform casedropping bootstrap.
#' @return An IndivBootnetSummary object.
#' @returns `boot_data` A matrix containing all the edge weights estimated in each bootstrap replicate.
#'   Only returned for "nonparametric" bootstrap.
#' @returns `boot_data_summary` A matrix containing summary of all bootstrap results. Only returned 
#'   for "nonparametric" bootstrap.
#' @returns `edge_data` A matrix containing all edge weights retained in the original constructed network that 
#'   estimated in each bootstrap replicate. Only returned for "nonparametric" bootstrap.
#' @returns `edge_data_summary` A matrix containing summary of all edge weights retained in the original constructed network.
#'   Only returned for "nonparametric" bootstrap.
#' @returns `edge_test` A matrix listing the test results of whether the edges are significantly different
#'   from each other. Only the selected edges in the IndivIsing object will be listed.
#'   Only returned for "nonparametric" bootstrap.
#' @returns `edge_quantile` A matrix listing the range of the differences between two estimated edges. 
#'   Only the selected edges in the IndivIsing object will be listed. Only returned for "nonparametric" bootstrap.
#' @returns `boot_centrality` A matrix summarizing the centrality information for each subject at each bootstrap. 
#'   Only returned for "nonparametric" bootstrap.
#' @returns `test_centrality` A matrix listing the stacked testing results for different centralities between 
#'   nodes for the first representative subject.
#' @returns `test_centrality_long` A matrix with the long format listing the stacked testing results for different centralities between 
#'   nodes for the first representative subject.
#' @returns `cor_results` Summary of the correlation results. Only returned for "casedropping" bootstrap.
#' @returns `time` Time used for computation.
#' @export
IndivBootSummary <- function(data,
                             IsingBootResult,
                             IsingResult,
                             nCores = 1,
                             library = .libPaths(),
                             verbose = TRUE,
                             sample_covar_mat){
  
  ##########################################################################
  ##########################################################################
  t0 <- Sys.time()
  
  nBoots <- length(IsingBootResult$bootResults)
  
  id_vec <- unique(data[,IsingBootResult$id])
  Np <- length(id_vec)
  
  if(IsingBootResult$type=="nonparametric"){
    
    y_names <- IsingBootResult$bootResults[[1]]$nodes
    x_names <- IsingBootResult$bootResults[[1]]$covar
    
    y_index <- IsingBootResult$bootResults[[1]]$y_index
    x_index <- IsingBootResult$bootResults[[1]]$x_index
    
    ##########################################################################
    ## summarize bootnet quantiles ###########################################
    thresholds <- do.call(rbind, lapply(1:nBoots, function(k) IsingBootResult$bootResults[[k]]$estimated_thresholds))
    boot_estimates <- do.call(rbind, lapply(1:nBoots, function(k) IsingBootResult$bootResults[[k]]$estimated_coeff_raw))
    
    edge_names <- NULL
    edge_weights <- NULL
    
    for(i in 1:length(y_index)){
      
      var_index <- (length(y_index)+1):(length(y_index)+length(x_index))
      
      edge_names <- c(edge_names, rep(paste0(y_names[i], "-bias"), times=nBoots))
      edge_weights <- c(edge_weights, thresholds[,i])
      
      edge_names <- c(edge_names, rep(paste0(y_names[i], "-bias", ":", x_names), times=nBoots))
      edge_weights <- c(edge_weights, do.call(c, lapply(1:nBoots, function(k) boot_estimates[i+(k-1)*length(y_index),var_index])))
      
      if(is.na(IsingResult$timepoint)){
        for(j in i:length(y_index)){
          if(j > i){
            var_index1 <- c(j, (length(y_index)+j*length(x_index)+1):(length(y_index)+(j+1)*length(x_index)))
            var_index2 <- c(i, (length(y_index)+i*length(x_index)+1):(length(y_index)+(i+1)*length(x_index)))
            
            edge_names <- c(edge_names, rep(c(paste0(y_names[i], "-", y_names[j]),
                                              paste0(y_names[i], "-", y_names[j], ":", x_names)),
                                            times=nBoots))
            if(IsingResult$AND==FALSE){
              edge_weights <- c(edge_weights, do.call(c,lapply(1:nBoots, function(k) (boot_estimates[i+(k-1)*length(y_index), var_index1]+boot_estimates[j+(k-1)*length(y_index), var_index2])/2)))
            }
            else if(IsingResult$AND==TRUE){
              edge_weights <- c(edge_weights, do.call(c,lapply(1:nBoots, function(k) ((boot_estimates[i+(k-1)*length(y_index), var_index1]+boot_estimates[j+(k-1)*length(y_index), var_index2])/2)*(boot_estimates[i+(k-1)*length(y_index), var_index1]!=0 & boot_estimates[j+(k-1)*length(y_index), var_index2]!=0))))
            }
          }
        }
      }
      else{ ## temporal network
        for(j in 1:length(y_index)){
          var_index <- c(j, (length(y_index)+j*length(x_index)+1):(length(y_index)+(j+1)*length(x_index)))
          edge_names <- c(edge_names, rep(c(paste0(y_names[i], "-", y_names[j]), 
                                            paste0(y_names[i], "-", y_names[j], ":", x_names)), 
                                          times=nBoots))
          
          edge_weights <- c(edge_weights, do.call(c, lapply(1:nBoots, function(k) boot_estimates[i+(k-1)*length(y_index), var_index])))
        }
      }
    }
    
    boot_data <- data.frame("edge_names" = edge_names, "edge_weights" = edge_weights)
    boot_data_summary <- boot_data %>% dplyr::group_by(edge_names) %>% 
      dplyr::summarise(mean=mean(edge_weights),
                lb=quantile(edge_weights, probs=0.025, type=6),
                ub=quantile(edge_weights, probs=0.975, type=6))
    boot_data_summary <- boot_data_summary[order(boot_data_summary$mean),]
    boot_data_summary$edge_names <- factor(boot_data_summary$edge_names, levels = boot_data_summary$edge_names)
    
    gc()
    ##########################################################################
    ##########################################################################
    
    select_edges <- NULL
    if(is.na(IsingResult$timepoint)){
      for(i in 1:(length(y_index)-1)){
        for(j in (i+1):length(y_index)){
          
          if(!is.na(IsingResult$estimated_formula[i,j])){
            str_vec <- strsplit(IsingResult$estimated_formula[i,j], "+", fixed = TRUE)[[1]]
            
            for(k in 1:length(str_vec)){
              if(!grepl(">>", str_vec[k], fixed = TRUE) & str_vec[k]!=""){
                select_edges <- c(select_edges, paste0(colnames(IsingResult$estimated_formula)[i], "-", 
                                                       colnames(IsingResult$estimated_formula)[j]))
              }
              else if(grepl(">>", str_vec[k], fixed = TRUE) & str_vec[k]!=""){
                select_edges <- c(select_edges, paste0(colnames(IsingResult$estimated_formula)[i], "-", 
                                                       colnames(IsingResult$estimated_formula)[j], ":",
                                                       sub(".*>>", "", str_vec[k])))
              }
            }
          }
        }
      }
    }else{
      for(i in 1:length(y_index)){
        for(j in 1:length(y_index)){
          
          if(!is.na(IsingResult$estimated_formula[i,j])){
            str_vec <- strsplit(IsingResult$estimated_formula[i,j], "+", fixed = TRUE)[[1]]
            
            for(k in 1:length(str_vec)){
              if(!grepl(">>", str_vec[k], fixed = TRUE) & str_vec[k]!=""){
                select_edges <- c(select_edges, paste0(colnames(IsingResult$estimated_formula)[i], "-", 
                                                       colnames(IsingResult$estimated_formula)[j]))
              }
              else if(grepl(">>", str_vec[k], fixed = TRUE) & str_vec[k]!=""){
                select_edges <- c(select_edges, paste0(colnames(IsingResult$estimated_formula)[i], "-", 
                                                       colnames(IsingResult$estimated_formula)[j], ":",
                                                       sub(".*>>", "", str_vec[k])))
              }
            } 
          }
        }
      }
    }
    
    edge_data <- boot_data[which(boot_data$edge_names %in% select_edges),]
    edge_data$edge_names <- factor(edge_data$edge_names, levels = unique(edge_data$edge_names))
    edge_data_summary <- boot_data_summary[which(boot_data_summary$edge_names %in% select_edges),]
    edge_data_summary$edge_names <- factor(edge_data_summary$edge_names, levels = unique(edge_data_summary$edge_names))
    
    edge_test <- as.data.frame(matrix(NA, ncol=length(select_edges), nrow=length(select_edges)))
    edge_quantile <- as.data.frame(matrix(NA, ncol=length(select_edges), nrow=length(select_edges)))
    colnames(edge_test) <- unique(edge_data$edge_names)
    rownames(edge_test) <- unique(edge_data$edge_names)
    colnames(edge_quantile) <- unique(edge_data$edge_names)
    rownames(edge_quantile) <- unique(edge_data$edge_names)
    for(i in 1:(length(select_edges)-1)){
      for(j in (i+1):length(select_edges)){
        
        edge_diff <- edge_data$edge_weights[which(edge_data$edge_names==colnames(edge_test)[i])]-
          edge_data$edge_weights[which(edge_data$edge_names==colnames(edge_test)[j])]
        
        edge_diff_lb <- quantile(edge_diff, probs = 0.025, type=6)
        edge_diff_ub <- quantile(edge_diff, probs = 0.975, type=6)
        
        if(edge_diff_lb*edge_diff_ub>0){
          edge_test[i,j] <- edge_test[j,i] <- 1
        }else{
          edge_test[i,j] <- edge_test[j,i] <- 0
        }
        
        edge_quantile[i,j] <- edge_quantile[j,i] <- paste0("(", format(round(edge_diff_lb,2), nsmall=2),",",
                                                           format(round(edge_diff_ub,2), nsmall=2),")")
      }
    }
    
    gc()
    
    ##########################################################################
    ## compare centrality
    ## use multiple core to save time
    # x_binary_check <- sapply(1:length(x_index), function(i) (length(table(data[,x_index[i]]))==2))
    # sample_covar_mat <- matrix(NA, nrow=2^(length(which(x_binary_check==TRUE))), ncol=length(x_index))
    # 
    # if(length(which(x_binary_check==FALSE))>0){
    #   x_num_value <- sapply(1:length(which(x_binary_check==FALSE)), function(j) mean(data[,x_index[which(x_binary_check==FALSE)[j]]]))  
    #   
    #   for(i in 1:length(which(x_binary_check==FALSE))){
    #     sample_covar_mat[,which(x_binary_check==FALSE)[i]] <- x_num_value[i]
    #   }
    # }
    # 
    # if(length(which(x_binary_check==TRUE))>0){
    #   expand_list <- rep(list(c(0,1)), length(which(x_binary_check==TRUE)))
    #   sample_covar_mat[,which(x_binary_check==TRUE)] <- as.matrix(expand.grid(expand_list[1:length(which(x_binary_check==TRUE))]))  
    # }
    
    if(missing(sample_covar_mat)){
      sample_covar_mat <- matrix(c(rep(0,length(x_index)),rep(1,length(x_index))),ncol=length(x_index), byrow = TRUE)
    }
    
    
    if(nCores==1){
      
      boot_network_list <- lapply(1:nBoots, function(j) 
        lapply(1:nrow(sample_covar_mat), function(i) IndivNetwork(IsingResult = IsingBootResult$bootResults[[j]], 
                                                                  covar_vec = as.vector(as.matrix(sample_covar_mat[i,])))))
      
      boot_centrality <- do.call(rbind, lapply(1:nBoots, function(j) 
        do.call(rbind, lapply(1:nrow(sample_covar_mat), function(i) boot_network_list[[j]][[i]]$node_centrality))))
      
      gc()
    }else{
      
      if(verbose){
        message("Bootstrapping...")
      }
      
      # if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) &&
      #     Sys.info()["sysname"] == "Darwin" && gsub("\\..*", "", getRversion()) == "4"){
      #   snow::setDefaultClusterOptions(setup_strategy = "sequential")
      # }
      # 
      # nClust <- nCores
      #cl <- snow::makeSOCKcluster(nClust)
      # cl <- snow::makeCluster(nClust)
      # 
      # excl <- c("prepFun", "prepArgs", "estFun", "estArgs",
      #           "graphFun", "graphArgs", "intFun", "intArgs")
      # parallel::clusterExport(cl, c(ls()[!ls() %in% c(excl, "cl")], "IndivNetwork"), envir = environment())
      
      # boot_network_list <- pbapply::pblapply(1:(nBoots*length(id_vec)), function(b) {
      #   
      #   .libPaths(library)
      #   
      #   return(IndivNetwork(IsingResult = IsingBootResult$bootResults[[ceiling(b/length(id_vec))]], 
      #                       data = data, 
      #                       target_id = id_vec[b-(ceiling(b/length(id_vec))-1)*length(id_vec)]))
      #   
      #   
      # }, cl=cl)
      
      # boot_network_list <- pbapply::pblapply(1:(nBoots*nrow(sample_covar_mat)), function(b) {
      #   
      #   .libPaths(library)
      #   
      #   return(IndivNetwork(IsingResult = IsingBootResult$bootResults[[ceiling(b/nrow(sample_covar_mat))]], 
      #                       covar_vec = as.vector(as.matrix(sample_covar_mat[b-(ceiling(b/nrow(sample_covar_mat))-1)*nrow(sample_covar_mat),])))) 
      #   
      # }, cl=cl)
      
      RNGkind("L'Ecuyer-CMRG")
      set.seed(seed)
      
      boot_network_list <- parallel::mclapply(1:(nBoots*nrow(sample_covar_mat)), function(b) {
        
        .libPaths(library)
        
        return(IndivNetwork(IsingResult = IsingBootResult$bootResults[[ceiling(b/nrow(sample_covar_mat))]], 
                            covar_vec = as.vector(as.matrix(sample_covar_mat[b-(ceiling(b/nrow(sample_covar_mat))-1)*nrow(sample_covar_mat),])))) 
        
      }, mc.cores=nCores)
      
      gc()
      
      boot_centrality <- do.call(rbind, lapply(1:(nBoots*nrow(sample_covar_mat)), function(i) boot_network_list[[i]]$node_centrality))
    }
    
    boot_centrality$boot <- rep(1:nBoots, each=length(IsingResult$nodes)*nrow(sample_covar_mat))
    boot_centrality$id <- rep(rep(c(1:nrow(sample_covar_mat)), each=length(IsingResult$nodes)), times=nBoots)
    
    ###################################
    ## test results for centralities for the first representative subject
    boot_centrality_id <- boot_centrality[boot_centrality$id==1,]
    
    if(IsingResult$networkModel=="static"){
      test_centrality_strength <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_strength) <- y_names
      rownames(test_centrality_strength) <- y_names
      
      test_centrality_expected_influence <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_expected_influence) <- y_names
      rownames(test_centrality_expected_influence) <- y_names
      
      test_centrality_betweenness <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_betweenness) <- y_names
      rownames(test_centrality_betweenness) <- y_names
      
      test_centrality_closeness <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_closeness) <- y_names
      rownames(test_centrality_closeness) <- y_names
      
      for(j in 1:(length(y_index)-1)){
        for(k in (j+1):length(y_index)){
          boot_centrality_id_node1 <- boot_centrality_id[seq(j,nrow(boot_centrality_id),length(y_index)),]
          boot_centrality_id_node2 <- boot_centrality_id[seq(k,nrow(boot_centrality_id),length(y_index)),]
          
          diff_vec_strength <- boot_centrality_id_node1$Strength-boot_centrality_id_node2$Strength
          diff_vec_expected_influence <- boot_centrality_id_node1$ExpectedInfluence-boot_centrality_id_node2$ExpectedInfluence
          diff_vec_betweennesse <- boot_centrality_id_node1$Betweenness-boot_centrality_id_node2$Betweenness
          diff_vec_closeness <- boot_centrality_id_node1$Closeness-boot_centrality_id_node2$Closeness
          
          if(as.vector(quantile(diff_vec_strength, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_strength, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_strength, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_strength, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_strength[j,k] <- 1
            test_centrality_strength[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_expected_influence, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_expected_influence, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_expected_influence, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_expected_influence, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_expected_influence[j,k] <- 1
            test_centrality_expected_influence[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_betweennesse, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_betweennesse, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_betweennesse, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_betweennesse, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_betweenness[j,k] <- 1
            test_centrality_betweenness[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_closeness, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_closeness, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_closeness, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_closeness, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_closeness[j,k] <- 1
            test_centrality_closeness[k,j] <- 1
          }
          
        }
      }
      
      test_centrality_strength_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                  "Y"=rep(y_names, times=length(y_names)),
                                                  "value"=as.vector(as.matrix(test_centrality_strength)))
      test_centrality_strength_long$value <- factor(test_centrality_strength_long$value)
      
      test_centrality_expected_influence_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                            "Y"=rep(y_names, times=length(y_names)),
                                                            "value"=as.vector(as.matrix(test_centrality_expected_influence)))
      test_centrality_expected_influence_long$value <- factor(test_centrality_expected_influence_long$value)
      
      test_centrality_betweenness_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                     "Y"=rep(y_names, times=length(y_names)),
                                                     "value"=as.vector(as.matrix(test_centrality_betweenness)))
      test_centrality_betweenness_long$value <- factor(test_centrality_betweenness_long$value)
      
      test_centrality_closeness_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                   "Y"=rep(y_names, times=length(y_names)),
                                                   "value"=as.vector(as.matrix(test_centrality_closeness)))
      test_centrality_closeness_long$value <- factor(test_centrality_closeness_long$value)
      
      test_centrality <- as.data.frame(rbind(test_centrality_strength,
                                             test_centrality_expected_influence,
                                             test_centrality_betweenness,
                                             test_centrality_closeness))
      test_centrality$centrality <- c(rep("Strength",length(y_index)),rep("ExpectedInfluence",length(y_index)),
                                      rep("Betweenness",length(y_index)),rep("Closeness",length(y_index)))
      
      test_centrality_long <- as.data.frame(rbind(test_centrality_strength_long,
                                                  test_centrality_expected_influence_long,
                                                  test_centrality_betweenness_long,
                                                  test_centrality_closeness_long))
      test_centrality_long$centrality <- c(rep("Strength",length(y_index)*length(y_index)),rep("ExpectedInfluence",length(y_index)*length(y_index)),
                                           rep("Betweenness",length(y_index)*length(y_index)),rep("Closeness",length(y_index)*length(y_index)))
    }else{
      test_centrality_in_strength <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_in_strength) <- y_names
      rownames(test_centrality_in_strength) <- y_names
      
      test_centrality_out_strength <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_out_strength) <- y_names
      rownames(test_centrality_out_strength) <- y_names
      
      test_centrality_in_expected_influence <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_in_expected_influence) <- y_names
      rownames(test_centrality_in_expected_influence) <- y_names
      
      test_centrality_out_expected_influence <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_out_expected_influence) <- y_names
      rownames(test_centrality_out_expected_influence) <- y_names
      
      test_centrality_betweenness <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_betweenness) <- y_names
      rownames(test_centrality_betweenness) <- y_names
      
      test_centrality_closeness <- matrix(0, nrow=length(y_index), ncol=length(y_index))
      colnames(test_centrality_closeness) <- y_names
      rownames(test_centrality_closeness) <- y_names
      
      for(j in 1:length(y_index)){
        for(k in 1:length(y_index)){
          boot_centrality_id_node1 <- boot_centrality_id[seq(j,nrow(boot_centrality_id),length(y_index)),]
          boot_centrality_id_node2 <- boot_centrality_id[seq(k,nrow(boot_centrality_id),length(y_index)),]
          
          diff_vec_in_strength <- boot_centrality_id_node1$InStrength-boot_centrality_id_node2$InStrength
          diff_vec_out_strength <- boot_centrality_id_node1$OutStrength-boot_centrality_id_node2$OutStrength
          diff_vec_in_expected_influence <- boot_centrality_id_node1$InExpectedInfluence-boot_centrality_id_node2$InExpectedInfluence
          diff_vec_out_expected_influence <- boot_centrality_id_node1$OutExpectedInfluence-boot_centrality_id_node2$OutExpectedInfluence
          diff_vec_betweennesse <- boot_centrality_id_node1$Betweenness-boot_centrality_id_node2$Betweenness
          diff_vec_closeness <- boot_centrality_id_node1$Closeness-boot_centrality_id_node2$Closeness
          
          if(as.vector(quantile(diff_vec_in_strength, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_in_strength, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_in_strength, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_in_strength, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_in_strength[j,k] <- 1
            test_centrality_in_strength[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_out_strength, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_out_strength, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_out_strength, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_out_strength, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_out_strength[j,k] <- 1
            test_centrality_out_strength[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_in_expected_influence, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_in_expected_influence, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_in_expected_influence, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_in_expected_influence, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_in_expected_influence[j,k] <- 1
            test_centrality_in_expected_influence[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_out_expected_influence, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_out_expected_influence, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_out_expected_influence, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_out_expected_influence, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_out_expected_influence[j,k] <- 1
            test_centrality_out_expected_influence[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_betweennesse, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_betweennesse, 0.975, type = 6, na.rm = TRUE))>0 & !is.na(as.vector(quantile(diff_vec_betweennesse, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_betweennesse, 0.975, type = 6, na.rm = TRUE)))){
            test_centrality_betweenness[j,k] <- 1
            test_centrality_betweenness[k,j] <- 1
          }
          
          if(as.vector(quantile(diff_vec_closeness, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_closeness, 0.975, type = 6, na.rm = TRUE))>0 & (!is.na(as.vector(quantile(diff_vec_closeness, 0.025, type = 6, na.rm = TRUE)*quantile(diff_vec_closeness, 0.975, type = 6, na.rm = TRUE))))){
            test_centrality_closeness[j,k] <- 1
            test_centrality_closeness[k,j] <- 1
          }
          
        }
      }
      
      test_centrality_in_strength_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                  "Y"=rep(y_names, times=length(y_names)),
                                                  "value"=as.vector(as.matrix(test_centrality_in_strength)))
      test_centrality_in_strength_long$value <- factor(test_centrality_in_strength_long$value)
      
      test_centrality_out_strength_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                     "Y"=rep(y_names, times=length(y_names)),
                                                     "value"=as.vector(as.matrix(test_centrality_out_strength)))
      test_centrality_out_strength_long$value <- factor(test_centrality_out_strength_long$value)
      
      test_centrality_in_expected_influence_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                            "Y"=rep(y_names, times=length(y_names)),
                                                            "value"=as.vector(as.matrix(test_centrality_in_expected_influence)))
      test_centrality_in_expected_influence_long$value <- factor(test_centrality_in_expected_influence_long$value)
      
      test_centrality_out_expected_influence_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                               "Y"=rep(y_names, times=length(y_names)),
                                                               "value"=as.vector(as.matrix(test_centrality_out_expected_influence)))
      test_centrality_out_expected_influence_long$value <- factor(test_centrality_out_expected_influence_long$value)
      
      test_centrality_betweenness_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                     "Y"=rep(y_names, times=length(y_names)),
                                                     "value"=as.vector(as.matrix(test_centrality_betweenness)))
      test_centrality_betweenness_long$value <- factor(test_centrality_betweenness_long$value)
      
      test_centrality_closeness_long <- data.frame("X"=rep(y_names, each=length(y_names)),
                                                   "Y"=rep(y_names, times=length(y_names)),
                                                   "value"=as.vector(as.matrix(test_centrality_closeness)))
      test_centrality_closeness_long$value <- factor(test_centrality_closeness_long$value)
      
      test_centrality <- as.data.frame(rbind(test_centrality_in_strength,
                                             test_centrality_out_strength,
                                             test_centrality_in_expected_influence,
                                             test_centrality_out_expected_influence,
                                             test_centrality_betweenness,
                                             test_centrality_closeness))
      test_centrality$centrality <- c(rep("InStrength",length(y_index)),rep("OutStrength",length(y_index)),
                                      rep("InExpectedInfluence",length(y_index)),rep("OutExpectedInfluence",length(y_index)),
                                      rep("Betweenness",length(y_index)),rep("Closeness",length(y_index)))
      
      test_centrality_long <- as.data.frame(rbind(test_centrality_in_strength_long,
                                                  test_centrality_out_strength_long,
                                                  test_centrality_in_expected_influence_long,
                                                  test_centrality_out_expected_influence_long,
                                                  test_centrality_betweenness_long,
                                                  test_centrality_closeness_long))
      test_centrality_long$centrality <- c(rep("InStrength",length(y_index)*length(y_index)),rep("OutStrength",length(y_index)*length(y_index)),
                                           rep("InExpectedInfluence",length(y_index)*length(y_index)),rep("OutExpectedInfluence",length(y_index)*length(y_index)),
                                           rep("Betweenness",length(y_index)*length(y_index)),rep("Closeness",length(y_index)*length(y_index)))
    }
    
    
    ###################################
    return(list("boot_data"=boot_data, 
                "boot_data_summary"=boot_data_summary, 
                "edge_data" = edge_data,
                "edge_data_summary" = edge_data_summary,
                "edge_test"= edge_test,
                "edge_quantile"=edge_quantile,
                "boot_centrality"=boot_centrality,
                "test_centrality"=test_centrality,
                "test_centrality_long"=test_centrality_long,
                "time" = Sys.time()-t0))
  }else if(IsingBootResult$type=="casedropping"){
    
    y_names <- IsingBootResult$bootResults[[1]][[1]]$nodes
    x_names <- IsingBootResult$bootResults[[1]][[1]]$covar
    
    y_index <- IsingBootResult$bootResults[[1]][[1]]$y_index
    x_index <- IsingBootResult$bootResults[[1]][[1]]$x_index
    
    sample_prob <- IsingBootResult$sample_prob
    
    ############################################################################
    # x_binary_check <- sapply(1:length(x_index), function(i) (length(table(data[,x_index[i]]))==2))
    # sample_covar_mat <- matrix(NA, nrow=2^(length(which(x_binary_check==TRUE))), ncol=length(x_index))
    # 
    # if(length(which(x_binary_check==FALSE))>0){
    #   x_num_value <- sapply(1:length(which(x_binary_check==FALSE)), function(j) mean(data[,x_index[which(x_binary_check==FALSE)[j]]]))  
    #   
    #   for(i in 1:length(which(x_binary_check==FALSE))){
    #     sample_covar_mat[,which(x_binary_check==FALSE)[i]] <- x_num_value[i]
    #   }
    # }
    # 
    # if(length(which(x_binary_check==TRUE))>0){
    #   expand_list <- rep(list(c(0,1)), length(which(x_binary_check==TRUE)))
    #   sample_covar_mat[,which(x_binary_check==TRUE)] <- as.matrix(expand.grid(expand_list[1:length(which(x_binary_check==TRUE))]))  
    # }
    
    if(missing(sample_covar_mat)){
      sample_covar_mat <- matrix(c(rep(0,length(x_index)),rep(1,length(x_index))),ncol=length(x_index), byrow = TRUE)
    }
    
    ############################################################################
    ind_network_list <- lapply(1:nrow(sample_covar_mat), function(i) IndivNetwork(IsingResult = IsingResult, 
                                                                                  covar_vec = as.vector(as.matrix(sample_covar_mat[i,]))))
    
    ############################################################################
    ## use multiple core to save time
    if(nCores==1){
      casedropping_network_func <- function(kk){ #i is the index of casedropping prob
        boot_network_func <- function(jj){ #j is the index of bootstrap
          boot_network_results <- lapply(1:nrow(sample_covar_mat), function(i) IndivNetwork(IsingResult = IsingBootResult$bootResults[[kk]][[jj]], 
                                                                                            covar_vec = as.vector(as.matrix(sample_covar_mat[i,]))))  
          return(boot_network_results)
        }
        return(lapply(1:length(sample_prob), function(j) boot_network_func(j)))
      }
      
      boot_network_list <- lapply(1:nBoots, function(k) casedropping_network_func(k))
      
      boot_centrality <- do.call(rbind, lapply(1:nBoots, function(k) 
        do.call(rbind, lapply(1:length(sample_prob), function(j) 
          do.call(rbind, lapply(1:nrow(sample_covar_mat), function(i) boot_network_list[[k]][[j]][[i]]$node_centrality))))))
      
      gc()
    }else{
      
      if(verbose){
        message("Bootstrapping...")
      }
      
      # if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) &&
      #     Sys.info()["sysname"] == "Darwin" && gsub("\\..*", "", getRversion()) == "4"){
      #   snow::setDefaultClusterOptions(setup_strategy = "sequential")
      # }
      # 
      # nClust <- nCores
      # cl <- snow::makeSOCKcluster(nClust)
      # #cl <- snow::makeCluster(nCluster)
      # 
      # excl <- c("prepFun", "prepArgs", "estFun", "estArgs",
      #           "graphFun", "graphArgs", "intFun", "intArgs")
      # parallel::clusterExport(cl, c(ls()[!ls() %in% c(excl, "cl")],"IndivNetwork"), envir = environment())
      
      RNGkind("L'Ecuyer-CMRG")
      set.seed(seed)
      
      # boot_network_list <- pbapply::pblapply(1:(length(sample_prob)*nBoots*length(id_vec)), function(b) {
      #   
      #   .libPaths(library)
      #   
      #   return(IndivNetwork(IsingResult = IsingBootResult$bootResults[[ceiling(b/length(id_vec))-(ceiling(ceiling(b/length(id_vec))/nBoots)-1)*nBoots]][[ceiling(b/(nBoots*length(id_vec)))]], 
      #                       data = data, #k is the index of subject
      #                       target_id = id_vec[b-length(id_vec)*(ceiling(b/length(id_vec))-1)]))
      # }, cl=cl)
      
      boot_network_list <- parallel::mclapply(1:(nBoots*length(sample_prob)*nrow(sample_covar_mat)), function(b) {
        
        .libPaths(library)
        
        return(IndivNetwork(IsingResult = IsingBootResult$bootResults[[ceiling(b/(length(sample_prob)*nrow(sample_covar_mat)))]][[ceiling(b/nrow(sample_covar_mat))-(ceiling(ceiling(b/nrow(sample_covar_mat))/length(sample_prob))-1)*length(sample_prob)]], 
                            data = data, #k is the index of subject
                            covar_vec = sample_covar_mat[b-nrow(sample_covar_mat)*(ceiling(b/nrow(sample_covar_mat))-1),]))
      }, mc.cores = nCores)
      
      gc()
      
      boot_centrality <- do.call(rbind, lapply(1:(nBoots*length(sample_prob)*nrow(sample_covar_mat)), function(i) if(!is(boot_network_list[[i]],"try-error")){
        return(boot_network_list[[i]]$node_centrality)
        }else{
          if(!is.na(IsingResult$timepoint)){
            node_mat <- as.data.frame(matrix(0,ncol=6,nrow=length(y_index)))
            colnames(node_mat) <- c("Betweenness","Closeness","InStrength","OutStrength","OutExpectedInfluence","InExpectedInfluence")
            rownames(node_mat) <- y_names
          }else{
            node_mat <- as.data.frame(matrix(0,ncol=4,nrow=length(y_index)))
            colnames(node_mat) <- c("Betweenness","Closeness","Strength","ExpectedInfluence")
            rownames(node_mat) <- y_names
          }
          return(node_mat)
          }))
    }
  
    ############################################################################
    boot_centrality$boot <- rep(1:nBoots, each=length(IsingResult$nodes)*length(sample_prob)*nrow(sample_covar_mat))
    boot_centrality$sample_prob <- rep(rep(sample_prob, each=length(IsingResult$nodes)*nrow(sample_covar_mat)), times=nBoots)
    boot_centrality$id <- rep(rep(c(1:nrow(sample_covar_mat)), each=length(IsingResult$nodes)), times=nBoots*length(sample_prob))
    
    ############################################################################
    if(IsingResult$networkModel=="static"){
      n_centrality <- 4
    }else{
      n_centrality <- 6
    }
    
    centrality_summary <- lapply(1:nBoots, function(k) 
      sapply(1:length(sample_prob), function(j) 
        sapply(1:nrow(sample_covar_mat), function(l) 
          sapply(1:n_centrality, function(i) cor.test(boot_centrality[boot_centrality$boot==k & boot_centrality$sample_prob==sample_prob[j] & boot_centrality$id==l,i], 
                                                      ind_network_list[[l]]$node_centrality[,i], method="spearman")$estimate))))
    cor_func <- function(i){
      
      mean_vec <- as.vector(sapply(1:length(sample_prob), function(j) apply(matrix(centrality_summary[[i]][,j], nrow=n_centrality, byrow = FALSE), 1, mean)))
      sd_vec <- as.vector(sapply(1:length(sample_prob), function(j) apply(matrix(centrality_summary[[i]][,j], nrow=n_centrality, byrow = FALSE), 1, sd)))
      
      if(IsingResult$networkModel=="static"){
        cor_mat <- data.frame("centrality"=c("Betweenness","Closeness","Strength","ExpectedInfluence"),
                              "mean"=mean_vec,
                              "sd"=sd_vec)  
      }else{
        cor_mat <- data.frame("centrality"=c("Betweenness","Closeness","InStrength","OutStrength","OutExpectedInfluence","InExpectedInfluence"),
                              "mean"=mean_vec,
                              "sd"=sd_vec)
      }
      
      return(cor_mat)
    }
    
    cor_final_results <- do.call(rbind, lapply(1:nBoots, function(i) cor_func(i)))
    cor_final_results$sample_prob <- rep(sample_prob, each=n_centrality)
    
    cor_final_results <- cor_final_results %>% dplyr::group_by(centrality, sample_prob) %>% dplyr::summarise(mean=mean(mean, na.rm=TRUE),
                                                                                                             sd=(sqrt(sum(sd^2)))/nBoots)
    
    gc()
    
    ############################################################################
    return(list("cor_final_results"=cor_final_results,
                "time" = Sys.time()-t0))
  }
  
}




